/*=======================================================================
// Below we will look at a simple example of how for... in and for... of
// work in JavaScript.
=======================================================================*/
let spaceXFlights = [
  "EchoStar 23",
  "SES-10",
  "NROL-76",
  "Inmarsat-5 F4",
  "CRS-11"
];

spaceXFlights.apiURL = "https://api.spacexdata.com/v2/launches";

// for... in loops over enumerable property names of an object.
for (let i in spaceXFlights) console.log(i);

// for... of uses an object-specific iterator and loops over
// the values generated by that.
for (let i of spaceXFlights) console.log(i);
